services:
  postgres_db:
    image: postgres:latest
    environment:
     - POSTGRES_USER=user
     - POSTGRES_PASSWORD=123
     - POSTGRES_DB=bookstore
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nambuinetwork
  web_crawler:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./output:/app/output  # Thư mục chứa tệp CSV, TXT
    depends_on:
      - postgres_db
    networks:
      - nambuinetwork

networks:
  nambuinetwork:
    driver: bridge